image: atlassian/default-image:latest

definitions:
  services:
    docker:
      memory: 2048
  caches:
    node-custom: node_modules
    sonar: ~/.sonar

clone:
  depth: full

pipelines:
  branches:
    main:
      - parallel:
          - step: &lint-step
              name: Lint and Style Check
              image: node:22.18.0
              caches:
                - node-custom
              script:
                - npm ci
                - npm run style-check
                - npm run lint
          - step: &sonarqube
              name: sonarqube
              image: sonarsource/sonar-scanner-cli:12
              runs-on:
                - self.hosted
                - linux
                - operation.internal
              caches:
                - sonar
              script:
                - sonar-scanner
                  -Dsonar.host.url=${SONAR_HOST_URL}
                  -Dsonar.token=${SONAR_TOKEN}
                  -Dsonar.projectKey=OmniCam

  pull-requests:
    "**":
      - parallel:
          - step:
              <<: *lint-step
          - step:
              <<: *sonarqube

  tags:
    "*":
      - parallel:
          - step: &build-push-frontend
              name: Build & Push Frontend
              services:
                - docker
              # Only runs if files inside /frontend change, OR if it's a manual custom build
              condition:
                changesets:
                  includePaths:
                    - "frontend/**"
                    - package-lock.json
                    - package.json
                    - protobufs
                    - nuxt.config.ts
                    - tailwind.config.js
                    - components.json
                    - tsconfig.json
              script:
                - docker login docker.io -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_ACCESS_TOKEN"
                - FINAL_TAG="${BITBUCKET_TAG:-${MANUAL_TAG:-manual-build}}"
                - docker build -t docker.io/oxygenai/omnicam_frontend:${FINAL_TAG} -t docker.io/oxygenai/omnicam_frontend:latest -f ./frontend/Dockerfile .
                - docker push docker.io/oxygenai/omnicam_frontend:${FINAL_TAG}
                - docker push docker.io/oxygenai/omnicam_frontend:latest

          - step: &build-push-backend
              name: Build & Push Backend
              services:
                - docker
              condition:
                changesets:
                  includePaths:
                    - "backend/**"
                    - .dockerignore
                    - go.mod
                    - go.sum
                    - sqlc.yaml
                    - "db/**"
                    - protobufs
              script:
                - docker login docker.io -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_ACCESS_TOKEN"
                - FINAL_TAG="${BITBUCKET_TAG:-${MANUAL_TAG:-manual-build}}"
                - docker build -t docker.io/oxygenai/omnicam_backend:${FINAL_TAG} -t docker.io/oxygenai/omnicam_backend:latest -f ./backend/Dockerfile .
                - docker push docker.io/oxygenai/omnicam_backend:${FINAL_TAG}
                - docker push docker.io/oxygenai/omnicam_backend:latest

          - step: &build-push-algo
              name: Build & Push Algo
              services:
                - docker
              condition:
                changesets:
                  includePaths:
                    - "predictive-algorithm/**"
              script:
                - docker login docker.io -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_ACCESS_TOKEN"
                - FINAL_TAG="${BITBUCKET_TAG:-${MANUAL_TAG:-manual-build}}"
                - docker build -t docker.io/oxygenai/omnicam_algo:${FINAL_TAG} -t docker.io/oxygenai/omnicam_algo:latest -f ./predictive-algorithm/Dockerfile .
                - docker push docker.io/oxygenai/omnicam_algo:${FINAL_TAG}
                - docker push docker.io/oxygenai/omnicam_algo:latest

          - step: &build-push-data-migration
              name: Build & Push Data Migration
              services:
                - docker
              condition:
                changesets:
                  includePaths:
                    - "db/**"
              script:
                - docker login docker.io -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_ACCESS_TOKEN"
                - FINAL_TAG="${BITBUCKET_TAG:-${MANUAL_TAG:-manual-build}}"
                - docker build -t docker.io/oxygenai/omnicam_data_migration:${FINAL_TAG} -t docker.io/oxygenai/omnicam_data_migration:latest -f ./db/Dockerfile .
                - docker push docker.io/oxygenai/omnicam_data_migration:${FINAL_TAG}
                - docker push docker.io/oxygenai/omnicam_data_migration:latest

  custom:
    manual-release-build:
      - variables:
          - name: MANUAL_TAG
            default: "manual-build"
            description: "Custom tag for the image"
      - parallel:
          - step: *build-push-algo
          - step: *build-push-frontend
          - step: *build-push-backend
          - step: *build-push-data-migration
