# If you want to use pre-built images, set env IMAGE_TAG=v0.0.1b
# IMAGE_TAG=v0.0.1b docker-compose up

name: omnicam-services

services:
  db:
    image: postgres:17
    container_name: omnicam_postgres
    env_file:
      - db/.env.prod
    ports:
      - "5433:5432"
    networks:
      - dmz_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    env_file:
      - ./backend/.env.prod
    entrypoint: ["/bin/sh", "-c"]
    command:
      ["migrate -path /migrations -database $$DATABASE_URL?sslmode=disable up"]
    networks:
      - dmz_net
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: ghcr.io/ministry-of-learning-of-jura-kites/omnicam_backend:${IMAGE_TAG:-latest}
    container_name: omnicam_backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    networks:
      - dmz_net
      - private_net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: ghcr.io/ministry-of-learning-of-jura-kites/omnicam_frontend:${IMAGE_TAG:-latest}
    container_name: omnicam_frontend
    env_file:
      - ./frontend/.env.prod
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - backend
    networks:
      - dmz_net

  optimization:
    build:
      context: .
      dockerfile: ./predictive-algorithm/Dockerfile
    image: ghcr.io/ministry-of-learning-of-jura-kites/omnicam_algo:${IMAGE_TAG:-latest}
    container_name: omnicam_algo
    env_file:
      - ./predictive-algorithm/.env.prod
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - private_net

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

networks:
  dmz_net:
  private_net:

volumes:
  postgres_data:
  uploads:
