# If you want to use pre-built images, set env IMAGE_TAG=v0.0.1b
# IMAGE_TAG=v0.0.1b docker-compose up

name: omnicam-services

services:
  db:
    image: postgres:17
    container_name: omnicam_postgres
    env_file:
      - db/.env.prod
    ports:
      - "15433:5432"
    networks:
      - private_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    env_file:
      - ./backend/.env.prod
    entrypoint: ["/bin/sh", "-c"]
    command:
      ["migrate -path /migrations -database $$DATABASE_URL?sslmode=disable up"]
    networks:
      - private_net
    depends_on:
      db:
        condition: service_healthy

  nats:
    image: nats:2.12.6-alpine
    container_name: omnicam_nats
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP Management/Monitoring port
    restart: always
    command: ["-m", "8222"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8222/healthz",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - private_net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: ghcr.io/ministry-of-learning-of-jura-kites/omnicam_backend:${IMAGE_TAG:-latest}
    container_name: omnicam_backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      app_net:
        aliases:
          - backend
      private_net:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: ghcr.io/ministry-of-learning-of-jura-kites/omnicam_frontend:${IMAGE_TAG:-latest}
    container_name: omnicam_frontend
    env_file:
      - ./frontend/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app_net
      - public_net

  optimization:
    build:
      context: .
      dockerfile: ./predictive-algorithm/Dockerfile
    image: ghcr.io/ministry-of-learning-of-jura-kites/omnicam_algo:${IMAGE_TAG:-latest}
    container_name: omnicam_algo
    env_file:
      - ./predictive-algorithm/.env.prod
    ports:
      - "8081:8081"
    depends_on:
      nats:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - private_net

networks:
  private_net:
  public_net:
  app_net:

volumes:
  postgres_data:
  uploads:
