export const SPECTATOR_MOVING_SENTIVITY = 0.02;

export const SPECTATOR_ROTAING_SENTIVITY = 0.01;

export const SPECTATOR_ADJ_INPUT_SENTIVITY = 0.01;

export const MOVING_ARROW_CONFIG = {
  HEAD_RADIUS: 0.05,
  HEAD_LENGTH: 0.1,
  CYLINDER_RADIUS: 0.03,
  CYLINDER_LENGTH: 4,

  DRAGGING_SENTIVITY: 0.005,
};

export const ROTATING_TORUS_CONFIG = {
  RADIUS: 1,
  TUBE_RADIUS: 0.05,
};
