@startuml Omnicam Class Diagram
class User {
    +userId: uuid
    +name: string
    +email : string
    +username : string
    +firstName : string
    +lastName : string
    +createWorkspace()
    +readWorkspace()
    +updateWorkspace()
    +deleteWorkspace()
}

class ProjectUserRole {
    +role: enum {Owner, Project Manager, Collaborator, <color:red>(Not Yet Implemented) Reader</color>}
}

class Project {
    +projectId: uuid
    +name: string
    +addUser(user: User,role: ProjectUserRole)
    +createProject()
    +readProject()
    +updateProject()
    +deleteProject()
}

class Model {
    +modelId: uuid
    +name: string
    +version: int
    +createModel()
    +readModel()
    +updateModel()
    +deleteModel()
    +saveChanges()
}

class Camera {
    +cameraId: uuid
    +name: string
    +angleX: float
    +angleY: float
    +angleZ: float
    +angleW: float
    +posX: float
    +posY: float
    +posZ: float
    +fov: float
    +frustumColor: RGB
    +frustumLength: float
    +isHidingArrows: boolean
    +isHidingWheels: boolean
    +isLockingPosition: boolean
    +isLockingRotation: boolean
    +isHidingFrustum: boolean
    +aspectWidth: float
    +aspectHeight: float
    +create()
    +update()
    +delete()
    +moveCamera()
    +rotateCamera()
}

class Workspace {
    +workspaceId: uuid
    +userId: uuid
    +modelId: uuid
    +cameras: Camera[]
    +baseCameras: Camera[]
    +version: int
    +baseVersion: int
    +autosave()
    +tryMergeIntoModel()
    +resolveConflict()
}

' Relationships
Project "1" -- "1..*" Model
Model "1" *-- "0..*" Camera
Workspace "0..*" --* "1" User
Workspace "0..*" --* "1" Model
User "1" -- "0..*" ProjectUserRole
Project "1" -- "0..*" ProjectUserRole

@enduml
