@startuml OmniCam System Architecture Diagram
left to right direction

actor User

package "Client Application" {
  [Web UI / Desktop UI] as UI
}

package "Backend Service" {
  [Auth Module] as Auth
  [Model Module] as Model
  [Project Module] as Project
  together {
    [Workspace Module] as Workspace
    [Livestream Module] as Livestream #red
  }
  [Camera Module] as Camera
}

package "Batch Persistence Service"  #red {
  [Batch Updater] as BatchUpdater  #red
}

package "Data Storage" {
  [Database\n(Users, Projects, Models, Cameras, Workspaces)] as DB
  [File System\n(Binary Assets)] as Repo
}

package "Messaging" #red {
  [Message Queue\n(Workspace Updates)] as MessageQueue  #red
}

' Actors interact with UI
User --> UI

' Client calls backend
UI <--> Workspace
UI <-> Livestream
UI --> Auth
UI --> Project
UI --> Model
UI --> Camera

' Workspace Livestream
Workspace <-> Livestream
BatchUpdater <- MessageQueue
BatchUpdater -down-> DB

' Backend to storage
Auth <-> DB
Project <-> DB
Project <-> Repo
Model <-> DB
Model <-> Repo
Workspace -> MessageQueue
Livestream <-> MessageQueue
Camera <--> DB

@enduml
