@startuml system architecture diagram
left to right direction

actor Owner
actor Collaborator as User

package "Client Application" {
  [Web UI / Desktop UI] as UI
}

package "Backend Service" {
  [Auth Module] as Auth
  [Model Module] as Model
  [Project Module] as Project
  [Workspace Module] as Workspace
  [Camera Module] as Camera
  [Livestream Module] as Livestream
}

package "Batch Persistence Service"{
  [Batch Updater] as BatchUpdater
}

package "Data Storage" {
  [Database\n(Users, Projects, Models, Cameras, Workspaces)] as DB
  [Model File System\n(3D Assets)] as Repo
}

package "Messaging" {
  [Message Queue\n(Workspace Updates)] as MessageQueue
}

' Actors interact with UI
Owner --> UI
User --> UI

' Client calls backend
UI --> Auth
UI --> Project
UI --> Model
UI <--> Workspace
UI --> Camera

' Workspace Livestream
Workspace <-> Livestream
Livestream <-> MessageQueue
BatchUpdater <- MessageQueue
BatchUpdater -down-> DB

' Backend to storage
Auth <-> DB
Project <-> DB
Model <-> DB
Model <-> Repo
Workspace <-> DB
Camera <--> DB
Camera <--> Repo

@enduml
