openapi: "3.1.1"
info:
  title: "OmniCam API overview"
  "version": "1.0.0"
servers:
  - url: https://localhost:8080/api/v1
    description: Dev Server
paths:
  "/":
    get:
      summary: "Select projects"
      description: Retrieves a list of all users in the system.
      responses:
        "200":
          description: A list of users
          content:
            application/json:
