on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Lowercase Owner
        run: echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV
      - name: Build frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/omnicam_frontend:${{ github.ref_name }}
            ghcr.io/${{ env.OWNER_LC }}/omnicam_frontend:latest

      - name: Build backend
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/omnicam_backend:${{ github.ref_name }}
            ghcr.io/${{ env.OWNER_LC }}/omnicam_backend:latest

      - name: Build algo
        uses: docker/build-push-action@v2
        with:
          context: predictive-algorithm
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/omnicam_algo:${{ github.ref_name }}
            ghcr.io/${{ env.OWNER_LC }}/omnicam_algo:latest
