on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      manual_tag:
        description: "Custom tag for the image"
        required: false
        default: "manual-build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Lowercase Owner
        id: prep
        run: |
          OWNER="${{ github.repository_owner }}"
          echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "FINAL_TAG=${{ github.event.inputs.manual_tag }}" >> $GITHUB_ENV
          else
            echo "FINAL_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Build frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/omnicam_frontend:${{ env.FINAL_TAG }}
            ghcr.io/${{ env.OWNER_LC }}/omnicam_frontend:latest

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/omnicam_backend:${{ env.FINAL_TAG }}
            ghcr.io/${{ env.OWNER_LC }}/omnicam_backend:latest

      - name: Build algo
        uses: docker/build-push-action@v6
        with:
          context: predictive-algorithm
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/omnicam_algo:${{ env.FINAL_TAG }}
            ghcr.io/${{ env.OWNER_LC }}/omnicam_algo:latest
